### PR TITLE
Implement expand-path

### LINKED ISSUE #14: Implement Shadowlisp's expand-path
It's [documented](https://shopify.github.io/shadowenv/shadowlisp/#expand-path) but in actuality it's just a stub currently.

`(expand-path "~/foo")` should be `"/Users/me/foo"`. I'd expect this to work approximately like `File.expand_path(x)` in ruby.

### PR DESCRIPTION
**Pull request by paarthmadan**
Closes #14

#### What was done?
Implement the expand-path utility. For the most part, I used other implemented functions as a reference point. I was initially planning on using the `ketos_fn2` macro, but decided against doing so as this utility needs to assert the length of its arguments.

#### For Reviewers
I'd encourage you to focus on the semantics of how the expansion is done (first tilde expansion, followed by canonicalization), and test a bunch of unique edge cases. 

#### How I 🎩'd
I setup a test directory with the following Shadowlisp file:
```lisp
(env/set "CANON" (expand-path "~/Documents/../src/github.com/paarthmadan"))
(env/set "TILDE" (expand-path "~/Documents"))
(env/set "BOTH" (expand-path "~/Documents/Shopify/../.."))
(env/set "SYMLINK" (expand-path "../../../../.vim"))
```
and upon entering the directory, the following values for ENV variables were set:
```sh
echo $CANON && echo $TILDE && echo $BOTH && echo $SYMLINK
/Users/paarthmadan/src/github.com/paarthmadan
/Users/paarthmadan/Documents
/Users/paarthmadan
/Users/paarthmadan/src/github.com/paarthmadan/dotfiles/vim
```

I'm fairly new to rust, so I'm open to refactoring / rewriting the implementation if it's not Rust-esque.

### CODE REVIEW

**Comment by paarthmadan** [comment]
Also, my build is failing on [this step](https://github.com/Shopify/shadowenv/runs/255588966#step:4:1). Any thoughts?

**Comment by lavoiesl** [comment]
Please rebase on top of master to pickup https://github.com/Shopify/shadowenv/pull/58

**Comment by paarthmadan** [comment]
> Can you commit your test data somewhere so we can have some fixtures if and when we get to writing tests for this package?

@lavoiesl Most of the testing I did was with existing files and directories on my local machine, so my worry is the Shadowlisp config I used is highly irrelevant in any other context. Do you think it would still be of value to commit it. Here's a gist with the file: https://gist.github.com/paarthmadan/f7e49a7f891fe03909b66a287cb9733e

**Comment by lavoiesl** [comment]
Ah, you're right, it's mostly home stuff.

All good 👍

**Pull request merged**
